AWSTemplateFormatVersion: '2010-09-09'
Description: Simple CloudFormation Template for an EC2 Instance

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-09ccb67fcbf1d625c 
      SecurityGroups:
        - Ref: MySecurityGroup


